server:
  port: 8081

spring:
  application:
    name: productos-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.pedidos360: INFO
